BEGIN;

CREATE TABLE pago_prestamo (
    idpagoprestamo integer GENERATED BY DEFAULT AS IDENTITY,
    idprestamo integer NOT NULL,
    idmetodopago integer NULL,
    fechapago timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    montopagado numeric(12,2) NOT NULL,
    numeroreferencia varchar(80),
    observacion varchar(255),
    estado varchar(20) NOT NULL DEFAULT 'Registrado',

    PRIMARY KEY (idpagoprestamo),

    FOREIGN KEY (idprestamo)
        REFERENCES prestamo(idprestamo),

    FOREIGN KEY (idmetodopago)
        REFERENCES metodopago(idmetodopago),

    CHECK (montopagado > 0),

    CHECK (estado IN ('Registrado', 'Anulado'))
);

CREATE INDEX idx_pago_prestamo_prestamo_estado
    ON pago_prestamo(idprestamo, estado);

CREATE INDEX idx_pago_prestamo_fecha
    ON pago_prestamo(fechapago);

COMMIT;
