BEGIN;

CREATE TABLE bingo_cierre_financiero (
    idbingocierrefinanciero integer GENERATED BY DEFAULT AS IDENTITY,

    idbingo integer NOT NULL,
    estado varchar(20) NOT NULL DEFAULT 'Abierto',

    cartonesvendidosunicos integer NOT NULL DEFAULT 0,
    recaudacionregistrada numeric(12,2) NOT NULL DEFAULT 0,
    premiosefectivofinalizados numeric(12,2) NOT NULL DEFAULT 0,
    costospremiosmateriales numeric(12,2) NOT NULL DEFAULT 0,
    gastosoperativos numeric(12,2) NOT NULL DEFAULT 0,

    resultadoprovisional numeric(12,2) NOT NULL DEFAULT 0,
    utilidadbruta numeric(12,2) NOT NULL DEFAULT 0,
    utilidadneta numeric(12,2) NOT NULL DEFAULT 0,

    totalrondas integer NOT NULL DEFAULT 0,
    rondasfinalizadas integer NOT NULL DEFAULT 0,
    rondascanceladas integer NOT NULL DEFAULT 0,
    rondaspendientes integer NOT NULL DEFAULT 0,

    fechacalculo timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechacierre timestamp without time zone,
    idusuariocierre integer,
    observacioncierre varchar(500),

    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT bingo_cierre_financiero_pkey
        PRIMARY KEY (idbingocierrefinanciero),

    CONSTRAINT uq_bcf_bingo
        UNIQUE (idbingo),

    CONSTRAINT fk_bcf_bingo
        FOREIGN KEY (idbingo)
        REFERENCES bingo(idbingo),

    CONSTRAINT fk_bcf_usuario_cierre
        FOREIGN KEY (idusuariocierre)
        REFERENCES auth_user(id),

    CONSTRAINT chk_bcf_estado
        CHECK (estado IN ('Abierto', 'Cerrado')),

    CONSTRAINT chk_bcf_no_negativos
        CHECK (
            cartonesvendidosunicos >= 0
            AND recaudacionregistrada >= 0
            AND premiosefectivofinalizados >= 0
            AND costospremiosmateriales >= 0
            AND gastosoperativos >= 0
            AND totalrondas >= 0
            AND rondasfinalizadas >= 0
            AND rondascanceladas >= 0
            AND rondaspendientes >= 0
        ),

    CONSTRAINT chk_bcf_rondas
        CHECK (
            totalrondas =
            rondasfinalizadas + rondascanceladas + rondaspendientes
        ),

    CONSTRAINT chk_bcf_fechacierre
        CHECK (
            estado = 'Abierto'
            OR (
                fechacierre IS NOT NULL
                AND idusuariocierre IS NOT NULL
            )
        ),

    CONSTRAINT chk_bcf_formulas
        CHECK (
            resultadoprovisional =
                recaudacionregistrada - premiosefectivofinalizados

            AND utilidadbruta =
                recaudacionregistrada
                - premiosefectivofinalizados
                - costospremiosmateriales

            AND utilidadneta =
                utilidadbruta - gastosoperativos
        )
);

CREATE INDEX idx_bcf_estado
    ON bingo_cierre_financiero(estado);

COMMIT;
