BEGIN;

CREATE TABLE bingo_premio_material_costo (
    idbingopremiomaterialcosto integer GENERATED BY DEFAULT AS IDENTITY,

    idbingo integer NOT NULL,
    idpartidabingo integer NOT NULL,

    descripcionpremio varchar(150) NOT NULL,
    monto numeric(12,2) NOT NULL,

    estado varchar(20) NOT NULL DEFAULT 'Registrado',
    observacion varchar(300),

    idusuarioregistro integer NOT NULL,
    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    idusuarioanulacion integer,
    fechaanulacion timestamp without time zone,
    motivoanulacion varchar(300),

    CONSTRAINT bingo_premio_material_costo_pkey
        PRIMARY KEY (idbingopremiomaterialcosto),

    CONSTRAINT fk_bpmc_partida_bingo
        FOREIGN KEY (idpartidabingo, idbingo)
        REFERENCES partidabingo(idpartidabingo, idbingo),

    CONSTRAINT fk_bpmc_usuario_registro
        FOREIGN KEY (idusuarioregistro)
        REFERENCES auth_user(id),

    CONSTRAINT fk_bpmc_usuario_anulacion
        FOREIGN KEY (idusuarioanulacion)
        REFERENCES auth_user(id),

    CONSTRAINT chk_bpmc_descripcion
        CHECK (btrim(descripcionpremio) <> ''),

    CONSTRAINT chk_bpmc_monto
        CHECK (monto >= 0),

    CONSTRAINT chk_bpmc_estado
        CHECK (estado IN ('Registrado', 'Anulado')),

    CONSTRAINT chk_bpmc_donacion
        CHECK (
            monto > 0
            OR btrim(coalesce(observacion, '')) <> ''
        ),

    CONSTRAINT chk_bpmc_anulacion
        CHECK (
            (
                estado = 'Registrado'
                AND idusuarioanulacion IS NULL
                AND fechaanulacion IS NULL
                AND btrim(coalesce(motivoanulacion, '')) = ''
            )
            OR
            (
                estado = 'Anulado'
                AND idusuarioanulacion IS NOT NULL
                AND fechaanulacion IS NOT NULL
                AND btrim(coalesce(motivoanulacion, '')) <> ''
            )
        )
);

CREATE UNIQUE INDEX uq_bpmc_partida_registrada
    ON bingo_premio_material_costo(idpartidabingo)
    WHERE estado = 'Registrado';

CREATE INDEX idx_bpmc_bingo_estado
    ON bingo_premio_material_costo(idbingo, estado);

COMMIT;
