BEGIN;

ALTER TABLE prestamo
    ALTER COLUMN idprestamo ADD GENERATED BY DEFAULT AS IDENTITY;

DO $$
DECLARE
    sequence_name text;
    next_value bigint;
BEGIN
    sequence_name := pg_get_serial_sequence('prestamo', 'idprestamo');

    IF sequence_name IS NULL THEN
        RAISE EXCEPTION 'No identity sequence found for prestamo.idprestamo';
    END IF;

    SELECT GREATEST(COALESCE(MAX(idprestamo), 0) + 1, 1)
    INTO next_value
    FROM prestamo;

    PERFORM setval(sequence_name::regclass, next_value, false);
END;
$$;

COMMIT;
