BEGIN;

CREATE TABLE prestamo_garante (
    idprestamogarante integer GENERATED BY DEFAULT AS IDENTITY,
    idprestamo integer NOT NULL,
    idgarante integer NOT NULL,
    capacidadcalculada numeric(12,2) NOT NULL DEFAULT 0,
    fecharegistro timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado varchar(20) NOT NULL DEFAULT 'Activo',

    CONSTRAINT prestamo_garante_pkey
        PRIMARY KEY (idprestamogarante),

    CONSTRAINT fk_pg_prestamo
        FOREIGN KEY (idprestamo)
        REFERENCES prestamo(idprestamo),

    CONSTRAINT fk_pg_garante
        FOREIGN KEY (idgarante)
        REFERENCES socio(idsocio),

    CONSTRAINT uq_pg_prestamo_garante
        UNIQUE (idprestamo, idgarante),

    CONSTRAINT chk_pg_capacidadcalculada
        CHECK (capacidadcalculada >= 0),

    CONSTRAINT chk_pg_estado
        CHECK (estado IN ('Activo', 'Inactivo'))
);

CREATE INDEX idx_pg_prestamo_estado
    ON prestamo_garante(idprestamo, estado);

CREATE INDEX idx_pg_garante_estado
    ON prestamo_garante(idgarante, estado);

COMMIT;
