CREATE TABLE IF NOT EXISTS solicitud_socio (
    idsolicitud integer GENERATED BY DEFAULT AS IDENTITY,
    idjugador integer NOT NULL,
    idtiposocio integer,
    primernombresocio varchar(40) NOT NULL,
    segundonombresocio varchar(40),
    primerapellidosocio varchar(40) NOT NULL,
    segundoapellidosocio varchar(40) NOT NULL,
    cisocio varchar(10) NOT NULL,
    fechanacimientosocio date NOT NULL,
    telefonopersonalsocio varchar(25),
    telefonotrabajosocio varchar(25),
    direcciondomiciliosocio varchar(255) NOT NULL,
    direcciontrabajosocio varchar(255),
    sexosocio varchar(1),
    estado varchar(20) NOT NULL DEFAULT 'Pendiente',
    fechasolicitud timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecharespuesta timestamp without time zone,
    idusuarioadminrespuesta integer,
    observacion varchar(255),
    motivorechazo varchar(255),
    idsocioresultado integer,

    CONSTRAINT solicitud_socio_pkey
        PRIMARY KEY (idsolicitud),
    CONSTRAINT fk_solicitud_socio_jugador
        FOREIGN KEY (idjugador)
        REFERENCES jugador(idjugador),
    CONSTRAINT fk_solicitud_socio_tiposocio
        FOREIGN KEY (idtiposocio)
        REFERENCES tiposocio(idtiposocio),
    CONSTRAINT fk_solicitud_socio_admin_respuesta
        FOREIGN KEY (idusuarioadminrespuesta)
        REFERENCES auth_user(id),
    CONSTRAINT fk_solicitud_socio_resultado
        FOREIGN KEY (idsocioresultado)
        REFERENCES socio(idsocio),
    CONSTRAINT chk_solicitud_socio_estado
        CHECK (estado IN ('Pendiente', 'Aprobada', 'Rechazada')),
    CONSTRAINT chk_solicitud_socio_sexo
        CHECK (sexosocio IS NULL OR sexosocio IN ('H', 'M')),
    CONSTRAINT chk_solicitud_socio_respuesta
        CHECK (
            (
                estado = 'Pendiente'
                AND fecharespuesta IS NULL
                AND idusuarioadminrespuesta IS NULL
                AND idsocioresultado IS NULL
                AND btrim(coalesce(motivorechazo, '')) = ''
            )
            OR
            (
                estado = 'Aprobada'
                AND fecharespuesta IS NOT NULL
                AND idusuarioadminrespuesta IS NOT NULL
                AND idsocioresultado IS NOT NULL
                AND btrim(coalesce(motivorechazo, '')) = ''
            )
            OR
            (
                estado = 'Rechazada'
                AND fecharespuesta IS NOT NULL
                AND idusuarioadminrespuesta IS NOT NULL
                AND idsocioresultado IS NULL
                AND btrim(coalesce(motivorechazo, '')) <> ''
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_solicitud_socio_estado_fecha
    ON solicitud_socio(estado, fechasolicitud);

CREATE INDEX IF NOT EXISTS idx_solicitud_socio_jugador
    ON solicitud_socio(idjugador);

CREATE UNIQUE INDEX IF NOT EXISTS uq_solicitud_socio_jugador_pendiente
    ON solicitud_socio(idjugador)
    WHERE estado = 'Pendiente';

CREATE UNIQUE INDEX IF NOT EXISTS uq_solicitud_socio_cisocio_pendiente
    ON solicitud_socio(cisocio)
    WHERE estado = 'Pendiente';
