BEGIN;

CREATE TABLE bingo_gasto_operativo (
    idbingogastooperativo integer GENERATED BY DEFAULT AS IDENTITY,
    idbingo integer NOT NULL,
    concepto varchar(150) NOT NULL,
    monto numeric(12,2) NOT NULL,
    fechagasto timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado varchar(20) NOT NULL DEFAULT 'Registrado',
    observacion varchar(300),

    idusuarioregistro integer NOT NULL,
    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    idusuarioanulacion integer,
    fechaanulacion timestamp without time zone,
    motivoanulacion varchar(300),

    CONSTRAINT bingo_gasto_operativo_pkey
        PRIMARY KEY (idbingogastooperativo),

    CONSTRAINT fk_bgo_bingo
        FOREIGN KEY (idbingo)
        REFERENCES bingo(idbingo),

    CONSTRAINT fk_bgo_usuario_registro
        FOREIGN KEY (idusuarioregistro)
        REFERENCES auth_user(id),

    CONSTRAINT fk_bgo_usuario_anulacion
        FOREIGN KEY (idusuarioanulacion)
        REFERENCES auth_user(id),

    CONSTRAINT chk_bgo_concepto
        CHECK (btrim(concepto) <> ''),

    CONSTRAINT chk_bgo_monto
        CHECK (monto > 0),

    CONSTRAINT chk_bgo_estado
        CHECK (estado IN ('Registrado', 'Anulado')),

    CONSTRAINT chk_bgo_anulacion
        CHECK (
            (
                estado = 'Registrado'
                AND idusuarioanulacion IS NULL
                AND fechaanulacion IS NULL
                AND btrim(coalesce(motivoanulacion, '')) = ''
            )
            OR
            (
                estado = 'Anulado'
                AND idusuarioanulacion IS NOT NULL
                AND fechaanulacion IS NOT NULL
                AND btrim(coalesce(motivoanulacion, '')) <> ''
            )
        )
);

CREATE INDEX idx_bgo_bingo_estado
    ON bingo_gasto_operativo(idbingo, estado);

COMMIT;
