CREATE TABLE IF NOT EXISTS solicitud_pago_prestamo (
    idsolicitudpago integer GENERATED BY DEFAULT AS IDENTITY,
    idprestamo integer NOT NULL,
    idsocio integer NOT NULL,
    idjugador integer NOT NULL,
    idmetodopago integer,
    monto numeric(12,2) NOT NULL,
    referencia varchar(80) NOT NULL,
    rutacomprobante varchar(255),
    observacionsocio text,
    estado varchar(20) NOT NULL DEFAULT 'Pendiente',
    fechasolicitud timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecharespuesta timestamp without time zone,
    idusuarioadminrespuesta integer,
    motivorechazo text,
    observacionadmin text,
    idpagoprestamoresultado integer,

    CONSTRAINT solicitud_pago_prestamo_pkey
        PRIMARY KEY (idsolicitudpago),
    CONSTRAINT fk_solicitud_pago_prestamo_prestamo
        FOREIGN KEY (idprestamo)
        REFERENCES prestamo(idprestamo),
    CONSTRAINT fk_solicitud_pago_prestamo_socio
        FOREIGN KEY (idsocio)
        REFERENCES socio(idsocio),
    CONSTRAINT fk_solicitud_pago_prestamo_jugador
        FOREIGN KEY (idjugador)
        REFERENCES jugador(idjugador),
    CONSTRAINT fk_solicitud_pago_prestamo_metodo
        FOREIGN KEY (idmetodopago)
        REFERENCES metodopago(idmetodopago),
    CONSTRAINT fk_solicitud_pago_prestamo_admin_respuesta
        FOREIGN KEY (idusuarioadminrespuesta)
        REFERENCES auth_user(id),
    CONSTRAINT fk_solicitud_pago_prestamo_resultado
        FOREIGN KEY (idpagoprestamoresultado)
        REFERENCES pago_prestamo(idpagoprestamo),
    CONSTRAINT chk_solicitud_pago_prestamo_estado
        CHECK (estado IN ('Pendiente', 'Aprobada', 'Rechazada')),
    CONSTRAINT chk_solicitud_pago_prestamo_monto
        CHECK (monto > 0),
    CONSTRAINT chk_solicitud_pago_prestamo_referencia
        CHECK (btrim(referencia) <> ''),
    CONSTRAINT chk_solicitud_pago_prestamo_respuesta
        CHECK (
            (
                estado = 'Pendiente'
                AND fecharespuesta IS NULL
                AND idusuarioadminrespuesta IS NULL
                AND idpagoprestamoresultado IS NULL
                AND btrim(coalesce(motivorechazo, '')) = ''
            )
            OR
            (
                estado = 'Aprobada'
                AND fecharespuesta IS NOT NULL
                AND idusuarioadminrespuesta IS NOT NULL
                AND idpagoprestamoresultado IS NOT NULL
                AND btrim(coalesce(motivorechazo, '')) = ''
            )
            OR
            (
                estado = 'Rechazada'
                AND fecharespuesta IS NOT NULL
                AND idusuarioadminrespuesta IS NOT NULL
                AND idpagoprestamoresultado IS NULL
                AND btrim(coalesce(motivorechazo, '')) <> ''
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_solicitud_pago_prestamo_estado_fecha
    ON solicitud_pago_prestamo(estado, fechasolicitud);

CREATE INDEX IF NOT EXISTS idx_solicitud_pago_prestamo_socio
    ON solicitud_pago_prestamo(idsocio);

CREATE INDEX IF NOT EXISTS idx_solicitud_pago_prestamo_jugador
    ON solicitud_pago_prestamo(idjugador);

CREATE INDEX IF NOT EXISTS idx_solicitud_pago_prestamo_prestamo
    ON solicitud_pago_prestamo(idprestamo);

CREATE UNIQUE INDEX IF NOT EXISTS uq_solicitud_pago_prestamo_prestamo_pendiente
    ON solicitud_pago_prestamo(idprestamo)
    WHERE estado = 'Pendiente';
