-- Esquema minimo para pruebas financieras aisladas.
-- Ejecutar solo mediante config.test_runner.FinanceSchemaDiscoverRunner.

CREATE TABLE bingo (
    idbingo integer NOT NULL,
    titulobingo varchar(150) NOT NULL,
    fechaprogramadabingo timestamp without time zone NOT NULL,
    tipobingo varchar(20) NOT NULL,
    lugarbingo varchar(255),
    urlsesionbingo varchar(255),
    preciocarton numeric(10,2) NOT NULL,
    premiomayor numeric(10,2) NOT NULL,
    descripcionpremiomayor varchar(100) NOT NULL,
    estadobingo varchar(20) NOT NULL,
    rutaimagenpremiomayor varchar(300),
    urlvideopromocional varchar(300),
    descripcionpremios varchar(500),

    CONSTRAINT bingo_pkey PRIMARY KEY (idbingo),
    CONSTRAINT chk_bingo_estadobingo
        CHECK (estadobingo IN ('Programado', 'En Curso', 'Finalizado', 'Cancelado'))
);

CREATE TABLE jugador (
    idjugador integer NOT NULL,
    idsocio integer,
    avatarjugador varchar(255),
    aliasjugador varchar(100),
    correojugador varchar(200),
    fecharegistrojugador timestamp without time zone NOT NULL,
    saldocreditojugador numeric(10,2) NOT NULL,
    estadocuentajugador varchar(20) NOT NULL,

    CONSTRAINT jugador_pkey PRIMARY KEY (idjugador),
    CONSTRAINT uq_jugador_aliasjugador UNIQUE (aliasjugador),
    CONSTRAINT uq_jugador_correojugador UNIQUE (correojugador)
);

CREATE TABLE partidabingo (
    idpartidabingo integer NOT NULL,
    idbingo integer NOT NULL,
    idjugadorganador integer,
    nombreronda varchar(100) NOT NULL,
    valorefectivo numeric(10,2) NOT NULL,
    premiomaterial varchar(150) NOT NULL,
    estadopartida varchar(20) NOT NULL,
    patronganador varchar(20) NOT NULL DEFAULT 'carton_lleno',
    bolascantadas text NOT NULL,
    ultimabola integer NOT NULL,
    haydesempate boolean,
    idbingadores text,
    bolamayordesempate integer,
    horainicio timestamp without time zone NOT NULL,
    horafin timestamp without time zone,

    CONSTRAINT partidabingo_pkey PRIMARY KEY (idpartidabingo),
    CONSTRAINT fk_partidabingo_bingo
        FOREIGN KEY (idbingo)
        REFERENCES bingo(idbingo),
    CONSTRAINT fk_partidabingo_jugador
        FOREIGN KEY (idjugadorganador)
        REFERENCES jugador(idjugador),
    CONSTRAINT uq_partidabingo_idpartida_idbingo
        UNIQUE (idpartidabingo, idbingo),
    CONSTRAINT chk_partidabingo_estadopartida
        CHECK (
            estadopartida IN (
                'Programada',
                'En espera',
                'En curso',
                'Pausada',
                'Desempate',
                'Finalizada',
                'Cancelada'
            )
        ),
    CONSTRAINT chk_partidabingo_patronganador
        CHECK (
            patronganador IN (
                'carton_lleno',
                'linea_horizontal',
                'linea_vertical',
                'diagonal',
                'cuatro_esquinas',
                'cruz',
                'x'
            )
        )
);

CREATE INDEX idx_partidabingo_idbingo
    ON partidabingo(idbingo);

CREATE TABLE carton (
    idcarton integer NOT NULL,
    idjugador integer,
    idbingo integer NOT NULL,
    idpartida integer,
    codigocarton varchar(30) NOT NULL,
    matriznumeros text NOT NULL,
    indicevictoria integer DEFAULT 0,
    preciopagado numeric(10,2),
    fechacompra timestamp without time zone,
    estadocarton varchar(20) NOT NULL,

    CONSTRAINT carton_pkey PRIMARY KEY (idcarton),
    CONSTRAINT fk_carton_bingo
        FOREIGN KEY (idbingo)
        REFERENCES bingo(idbingo),
    CONSTRAINT fk_carton_jugador
        FOREIGN KEY (idjugador)
        REFERENCES jugador(idjugador),
    CONSTRAINT fk_carton_partidabingo
        FOREIGN KEY (idpartida)
        REFERENCES partidabingo(idpartidabingo),
    CONSTRAINT uq_carton_codigocarton UNIQUE (codigocarton),
    CONSTRAINT uq_carton_idcarton_idbingo UNIQUE (idcarton, idbingo),
    CONSTRAINT chk_carton_preciopagado
        CHECK (preciopagado >= 0)
);

CREATE INDEX idx_carton_idbingo
    ON carton(idbingo);

CREATE INDEX idx_carton_idjugador
    ON carton(idjugador);

CREATE TABLE carton_partida_bingo (
    idcartonpartidabingo integer GENERATED BY DEFAULT AS IDENTITY,
    idcarton integer NOT NULL,
    idpartida integer NOT NULL,
    idbingo integer NOT NULL,
    estado_participacion varchar(20) NOT NULL,
    indicevictoria integer,
    es_asignacion_original boolean NOT NULL DEFAULT false,
    origen_asignacion varchar(24) NOT NULL,
    motivoestado varchar(255),
    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechavalidacion timestamp without time zone,

    CONSTRAINT carton_partida_bingo_pkey
        PRIMARY KEY (idcartonpartidabingo),
    CONSTRAINT uq_cpb_carton_partida
        UNIQUE (idcarton, idpartida),
    CONSTRAINT fk_cpb_carton_bingo
        FOREIGN KEY (idcarton, idbingo)
        REFERENCES carton(idcarton, idbingo),
    CONSTRAINT fk_cpb_partida_bingo
        FOREIGN KEY (idpartida, idbingo)
        REFERENCES partidabingo(idpartidabingo, idbingo),
    CONSTRAINT chk_cpb_estado
        CHECK (
            estado_participacion IN (
                'Pendiente',
                'En juego',
                'Cerrado',
                'Ganador',
                'Anulado'
            )
        ),
    CONSTRAINT chk_cpb_indice
        CHECK (indicevictoria IS NULL OR indicevictoria > 0),
    CONSTRAINT chk_cpb_origen
        CHECK (origen_asignacion IN ('Historica original', 'Aplicacion')),
    CONSTRAINT chk_cpb_origen_original
        CHECK (
            (
                es_asignacion_original = true
                AND origen_asignacion = 'Historica original'
            )
            OR
            (
                es_asignacion_original = false
                AND origen_asignacion = 'Aplicacion'
            )
        )
);

CREATE INDEX idx_cpb_idpartida
    ON carton_partida_bingo(idpartida);

CREATE INDEX idx_cpb_idbingo
    ON carton_partida_bingo(idbingo);

CREATE INDEX idx_cpb_partida_estado
    ON carton_partida_bingo(idpartida, estado_participacion);

CREATE TABLE bingo_gasto_operativo (
    idbingogastooperativo integer GENERATED BY DEFAULT AS IDENTITY,
    idbingo integer NOT NULL,
    concepto varchar(150) NOT NULL,
    monto numeric(12,2) NOT NULL,
    fechagasto timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado varchar(20) NOT NULL DEFAULT 'Registrado',
    observacion varchar(300),
    idusuarioregistro integer NOT NULL,
    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idusuarioanulacion integer,
    fechaanulacion timestamp without time zone,
    motivoanulacion varchar(300),

    CONSTRAINT bingo_gasto_operativo_pkey
        PRIMARY KEY (idbingogastooperativo),
    CONSTRAINT fk_bgo_bingo
        FOREIGN KEY (idbingo)
        REFERENCES bingo(idbingo),
    CONSTRAINT fk_bgo_usuario_registro
        FOREIGN KEY (idusuarioregistro)
        REFERENCES auth_user(id),
    CONSTRAINT fk_bgo_usuario_anulacion
        FOREIGN KEY (idusuarioanulacion)
        REFERENCES auth_user(id),
    CONSTRAINT chk_bgo_concepto
        CHECK (btrim(concepto) <> ''),
    CONSTRAINT chk_bgo_monto
        CHECK (monto > 0),
    CONSTRAINT chk_bgo_estado
        CHECK (estado IN ('Registrado', 'Anulado')),
    CONSTRAINT chk_bgo_anulacion
        CHECK (
            (
                estado = 'Registrado'
                AND idusuarioanulacion IS NULL
                AND fechaanulacion IS NULL
                AND btrim(coalesce(motivoanulacion, '')) = ''
            )
            OR
            (
                estado = 'Anulado'
                AND idusuarioanulacion IS NOT NULL
                AND fechaanulacion IS NOT NULL
                AND btrim(coalesce(motivoanulacion, '')) <> ''
            )
        )
);

CREATE INDEX idx_bgo_bingo_estado
    ON bingo_gasto_operativo(idbingo, estado);

CREATE TABLE bingo_premio_material_costo (
    idbingopremiomaterialcosto integer GENERATED BY DEFAULT AS IDENTITY,
    idbingo integer NOT NULL,
    idpartidabingo integer NOT NULL,
    descripcionpremio varchar(150) NOT NULL,
    monto numeric(12,2) NOT NULL,
    estado varchar(20) NOT NULL DEFAULT 'Registrado',
    observacion varchar(300),
    idusuarioregistro integer NOT NULL,
    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idusuarioanulacion integer,
    fechaanulacion timestamp without time zone,
    motivoanulacion varchar(300),

    CONSTRAINT bingo_premio_material_costo_pkey
        PRIMARY KEY (idbingopremiomaterialcosto),
    CONSTRAINT fk_bpmc_partida_bingo
        FOREIGN KEY (idpartidabingo, idbingo)
        REFERENCES partidabingo(idpartidabingo, idbingo),
    CONSTRAINT fk_bpmc_usuario_registro
        FOREIGN KEY (idusuarioregistro)
        REFERENCES auth_user(id),
    CONSTRAINT fk_bpmc_usuario_anulacion
        FOREIGN KEY (idusuarioanulacion)
        REFERENCES auth_user(id),
    CONSTRAINT chk_bpmc_descripcion
        CHECK (btrim(descripcionpremio) <> ''),
    CONSTRAINT chk_bpmc_monto
        CHECK (monto >= 0),
    CONSTRAINT chk_bpmc_estado
        CHECK (estado IN ('Registrado', 'Anulado')),
    CONSTRAINT chk_bpmc_donacion
        CHECK (
            monto > 0
            OR btrim(coalesce(observacion, '')) <> ''
        ),
    CONSTRAINT chk_bpmc_anulacion
        CHECK (
            (
                estado = 'Registrado'
                AND idusuarioanulacion IS NULL
                AND fechaanulacion IS NULL
                AND btrim(coalesce(motivoanulacion, '')) = ''
            )
            OR
            (
                estado = 'Anulado'
                AND idusuarioanulacion IS NOT NULL
                AND fechaanulacion IS NOT NULL
                AND btrim(coalesce(motivoanulacion, '')) <> ''
            )
        )
);

CREATE UNIQUE INDEX uq_bpmc_partida_registrada
    ON bingo_premio_material_costo(idpartidabingo)
    WHERE estado = 'Registrado';

CREATE INDEX idx_bpmc_bingo_estado
    ON bingo_premio_material_costo(idbingo, estado);

CREATE TABLE bingo_cierre_financiero (
    idbingocierrefinanciero integer GENERATED BY DEFAULT AS IDENTITY,
    idbingo integer NOT NULL,
    estado varchar(20) NOT NULL DEFAULT 'Abierto',
    cartonesvendidosunicos integer NOT NULL DEFAULT 0,
    recaudacionregistrada numeric(12,2) NOT NULL DEFAULT 0,
    premiosefectivofinalizados numeric(12,2) NOT NULL DEFAULT 0,
    costospremiosmateriales numeric(12,2) NOT NULL DEFAULT 0,
    gastosoperativos numeric(12,2) NOT NULL DEFAULT 0,
    resultadoprovisional numeric(12,2) NOT NULL DEFAULT 0,
    utilidadbruta numeric(12,2) NOT NULL DEFAULT 0,
    utilidadneta numeric(12,2) NOT NULL DEFAULT 0,
    totalrondas integer NOT NULL DEFAULT 0,
    rondasfinalizadas integer NOT NULL DEFAULT 0,
    rondascanceladas integer NOT NULL DEFAULT 0,
    rondaspendientes integer NOT NULL DEFAULT 0,
    fechacalculo timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechacierre timestamp without time zone,
    idusuariocierre integer,
    observacioncierre varchar(500),
    fechacreacion timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT bingo_cierre_financiero_pkey
        PRIMARY KEY (idbingocierrefinanciero),
    CONSTRAINT uq_bcf_bingo
        UNIQUE (idbingo),
    CONSTRAINT fk_bcf_bingo
        FOREIGN KEY (idbingo)
        REFERENCES bingo(idbingo),
    CONSTRAINT fk_bcf_usuario_cierre
        FOREIGN KEY (idusuariocierre)
        REFERENCES auth_user(id),
    CONSTRAINT chk_bcf_estado
        CHECK (estado IN ('Abierto', 'Cerrado')),
    CONSTRAINT chk_bcf_no_negativos
        CHECK (
            cartonesvendidosunicos >= 0
            AND recaudacionregistrada >= 0
            AND premiosefectivofinalizados >= 0
            AND costospremiosmateriales >= 0
            AND gastosoperativos >= 0
            AND totalrondas >= 0
            AND rondasfinalizadas >= 0
            AND rondascanceladas >= 0
            AND rondaspendientes >= 0
        ),
    CONSTRAINT chk_bcf_rondas
        CHECK (
            totalrondas =
            rondasfinalizadas + rondascanceladas + rondaspendientes
        ),
    CONSTRAINT chk_bcf_fechacierre
        CHECK (
            estado = 'Abierto'
            OR (
                fechacierre IS NOT NULL
                AND idusuariocierre IS NOT NULL
            )
        ),
    CONSTRAINT chk_bcf_formulas
        CHECK (
            resultadoprovisional =
                recaudacionregistrada - premiosefectivofinalizados

            AND utilidadbruta =
                recaudacionregistrada
                - premiosefectivofinalizados
                - costospremiosmateriales

            AND utilidadneta =
                utilidadbruta - gastosoperativos
        )
);

CREATE INDEX idx_bcf_estado
    ON bingo_cierre_financiero(estado);
